# Spring settings
spring:
    profiles.active: dev

    kafka:
        bootstrap-servers: 192.168.3.201:9092,192.168.3.202:9092,192.168.3.203:9092
        consumer:
            group-id: qingCloud
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

        producer:
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer


kafkaMQ:
    data_number: ${DATA_NUMBER}
    thread_number: ${THREAD_NUMBER}